import type { Restaurant, Dish, Order, Review, DashboardStats, RevenueData } from "@/types"

export const mockRestaurants: Restaurant[] = [
  {
    id: "rest_1",
    name: "Phở Hà Nội",
    description: "Authentic Vietnamese pho with traditional recipes",
    image: "/vietnamese-pho-restaurant.png",
    address: "123 Nguyễn Huệ, Q.1, TP.HCM",
    phone: "0281234567",
    rating: 4.5,
    totalReviews: 234,
    isActive: true,
    openTime: "06:00",
    closeTime: "22:00",
    categories: ["Vietnamese", "Noodles"],
  },
  {
    id: "rest_2",
    name: "Cơm Tấm Sài Gòn",
    description: "Delicious broken rice with grilled pork",
    image: "/vietnamese-broken-rice-restaurant.jpg",
    address: "456 Lê Lợi, Q.1, TP.HCM",
    phone: "0281234568",
    rating: 4.7,
    totalReviews: 189,
    isActive: true,
    openTime: "07:00",
    closeTime: "21:00",
    categories: ["Vietnamese", "Rice"],
  },
  {
    id: "rest_3",
    name: "Bánh Mì 362",
    description: "Famous Vietnamese baguette sandwiches",
    image: "/vietnamese-banh-mi-sandwich-shop.jpg",
    address: "362 Hai Bà Trưng, Q.3, TP.HCM",
    phone: "0281234569",
    rating: 4.8,
    totalReviews: 456,
    isActive: true,
    openTime: "06:00",
    closeTime: "20:00",
    categories: ["Vietnamese", "Sandwiches"],
  },
]

export const mockDishes: Dish[] = [
  {
    id: "dish_1",
    restaurantId: "rest_1",
    name: "Phở Bò Tái",
    description: "Beef pho with rare beef slices",
    price: 55000,
    image: "/vietnamese-beef-pho-bowl.jpg",
    category: "Noodles",
    rating: 4.6,
    totalReviews: 89,
    isAvailable: false,
    spicyLevel: "none",
    tags: ["Popular", "Bò", "Món nước", "Đậm đà"],
  },
  {
    id: "dish_2",
    restaurantId: "rest_1",
    name: "Phở Gà",
    description: "Chicken pho with tender chicken",
    price: 50000,
    image: "/vietnamese-chicken-pho.jpg",
    category: "Noodles",
    rating: 4.4,
    totalReviews: 67,
    isAvailable: false,
    spicyLevel: "none",
    tags: ["Gà", "Món nước", "Thanh nhẹ"],
  },
  {
    id: "dish_3",
    restaurantId: "rest_2",
    name: "Cơm Tấm Sườn Bì Chả",
    description: "Broken rice with grilled pork, shredded pork skin, and egg meatloaf",
    price: 45000,
    image: "/vietnamese-broken-rice-with-grilled-pork.jpg",
    category: "Rice",
    rating: 4.7,
    totalReviews: 123,
    isAvailable: false,
    spicyLevel: "mild",
    tags: ["Popular", "Heo", "Món Việt", "Nướng"],
  },
  {
    id: "dish_4",
    restaurantId: "rest_2",
    name: "Cơm Tấm Sườn Nướng",
    description: "Broken rice with grilled pork chop",
    price: 40000,
    image: "/grilled-pork-chop-with-rice.jpg",
    category: "Rice",
    rating: 4.5,
    totalReviews: 98,
    isAvailable: false,
    spicyLevel: "none",
    tags: ["Heo", "Món Việt", "Nướng"],
  },
  {
    id: "dish_5",
    restaurantId: "rest_3",
    name: "Bánh Mì Thịt Nguội",
    description: "Vietnamese baguette with cold cuts",
    price: 25000,
    image: "/vietnamese-banh-mi-sandwich.jpg",
    category: "Sandwiches",
    rating: 4.8,
    totalReviews: 234,
    isAvailable: true,
    spicyLevel: "mild",
    tags: ["Popular", "Bánh mì", "Nhanh"],
  },
  {
    id: "dish_6",
    restaurantId: "rest_3",
    name: "Bánh Mì Xíu Mại",
    description: "Vietnamese baguette with meatballs",
    price: 30000,
    image: "/banh-mi-with-meatballs.jpg",
    category: "Sandwiches",
    rating: 4.6,
    totalReviews: 156,
    isAvailable: true,
    spicyLevel: "medium",
    tags: ["Xíu mại", "Bánh mì", "Nhanh"],
  },
  {
    id: "dish_wagyu_pho",
    restaurantId: "rest_1",
    name: "Phở Bò Wagyu",
    description:
      "Sợi phở mềm thơm kết hợp với thịt bò wagyu thái mỏng, nước dùng hầm 18 giờ cùng gừng nướng và quế hồi.",
    price: 95000,
    image: "/vietnamese-beef-pho-bowl.jpg",
    category: "Noodles",
    rating: 4.9,
    totalReviews: 142,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Signature", "Đậm đà", "Bò"],
  },
  {
    id: "dish_golden_chicken_pho",
    restaurantId: "rest_1",
    name: "Phở Gà Thả Vườn",
    description:
      "Gà thả vườn xé tay, nước dùng thanh ngọt từ xương ống và thảo mộc, thêm gừng rang tạo cảm giác ấm bụng.",
    price: 78000,
    image: "/vietnamese-chicken-pho.jpg",
    category: "Noodles",
    rating: 4.7,
    totalReviews: 95,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Thanh nhẹ", "Gà", "Buổi sáng"],
  },
  {
    id: "dish_crispy_short_rib",
    restaurantId: "rest_2",
    name: "Cơm Tấm Sườn Non Giòn",
    description:
      "Sườn non ướp mật ong áp chảo giòn cạnh, dưa chua làm thủ công và mỡ hành béo ngậy.",
    price: 63000,
    image: "/vietnamese-broken-rice-with-grilled-pork.jpg",
    category: "Rice",
    rating: 4.8,
    totalReviews: 210,
    isAvailable: true,
    spicyLevel: "mild",
    tags: ["Popular", "Heo", "Nướng"],
  },
  {
    id: "dish_salted_egg_rice",
    restaurantId: "rest_2",
    name: "Cơm Tấm Trứng Muối Sốt Bơ",
    description:
      "Thịt ba chỉ nướng sốt trứng muối béo nhưng không ngậy, ăn kèm cơm tấm hạt tơi và tóp mỡ cháy tỏi.",
    price: 69000,
    image: "/grilled-pork-chop-with-rice.jpg",
    category: "Rice",
    rating: 4.6,
    totalReviews: 132,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Sáng tạo", "Trứng muối", "Đậm đà"],
  },
  {
    id: "dish_sweety_pork_rice",
    restaurantId: "rest_2",
    name: "Cơm Tấm Sườn Rim Dừa",
    description:
      "Sườn rim nước dừa Bến Tre, thơm mùi lá chanh kèm đồ chua giấm táo cân bằng vị ngọt.",
    price: 60000,
    image: "/vietnamese-broken-rice-with-grilled-pork.jpg",
    category: "Rice",
    rating: 4.5,
    totalReviews: 88,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Ngọt dịu", "Heo", "Gia đình"],
  },
  {
    id: "dish_banh_mi_pate_foie",
    restaurantId: "rest_3",
    name: "Bánh Mì Pate Gan Ngỗng",
    description:
      "Ổ bánh mì vỏ giòn nhân pate gan ngỗng béo ngậy, dưa leo ngâm giấm và rau thơm cắt tay.",
    price: 55000,
    image: "/vietnamese-banh-mi-sandwich.jpg",
    category: "Sandwiches",
    rating: 4.9,
    totalReviews: 167,
    isAvailable: true,
    spicyLevel: "mild",
    tags: ["Signature", "Bánh mì", "Ăn sáng"],
  },
  {
    id: "dish_banh_mi_grilled_chicken",
    restaurantId: "rest_3",
    name: "Bánh Mì Gà Nướng Lá Chanh",
    description:
      "Gà nướng lá chanh thơm ngát, sốt mayonnaise tỏi và đồ chua cắt sợi tạo nên chiếc bánh mì cân bằng vị.",
    price: 42000,
    image: "/vietnamese-banh-mi-sandwich.jpg",
    category: "Sandwiches",
    rating: 4.7,
    totalReviews: 143,
    isAvailable: true,
    spicyLevel: "mild",
    tags: ["Gà", "Đường phố", "Nhanh"],
  },
  {
    id: "dish_banh_mi_caramel_pork",
    restaurantId: "rest_3",
    name: "Bánh Mì Thịt Kho Trứng",
    description:
      "Thịt ba chỉ kho kẹo, trứng vịt thấm nước dừa ăn cùng pate và đồ chua trong ổ bánh mì giòn.",
    price: 45000,
    image: "/banh-mi-with-meatballs.jpg",
    category: "Sandwiches",
    rating: 4.5,
    totalReviews: 98,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Heo", "Comfort", "Gia truyền"],
  },
  {
    id: "dish_spicy_pho_sate",
    restaurantId: "rest_1",
    name: "Phở Bò Sa Tế Đà Nẵng",
    description:
      "Nước dùng đậm vị sa tế, gân bò hầm mềm, rau thơm và hành phi giòn rụm kích thích vị giác.",
    price: 82000,
    image: "/vietnamese-beef-pho-bowl.jpg",
    category: "Noodles",
    rating: 4.8,
    totalReviews: 176,
    isAvailable: true,
    spicyLevel: "hot",
    tags: ["Cay", "Bò", "Đặc biệt"],
  },
  {
    id: "dish_crab_pho",
    restaurantId: "rest_1",
    name: "Phở Riêu Cua Đồng",
    description:
      "Nước phở trong thanh kết hợp riêu cua đồng thơm lừng, thêm cà chua chưng và hành thì là.",
    price: 76000,
    image: "/vietnamese-chicken-pho.jpg",
    category: "Noodles",
    rating: 4.5,
    totalReviews: 74,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Thanh", "Cua", "Đặc sắc"],
  },
  {
    id: "dish_pandan_rice",
    restaurantId: "rest_2",
    name: "Cơm Tấm Lá Dứa Hải Sản",
    description:
      "Cơm tấm hấp lá dứa, topping tôm sú sốt bơ tỏi và chả cua dùng kèm sốt me cay nhẹ.",
    price: 78000,
    image: "/grilled-pork-chop-with-rice.jpg",
    category: "Rice",
    rating: 4.7,
    totalReviews: 121,
    isAvailable: true,
    spicyLevel: "medium",
    tags: ["Hải sản", "Thơm lừng", "Đặc biệt"],
  },
  {
    id: "dish_veggie_banh_mi",
    restaurantId: "rest_3",
    name: "Bánh Mì Nấm Đậu Phụ",
    description:
      "Nhân nấm đùi gà xào xì dầu, đậu phụ chiên giòn, sốt tương đen và rau củ ngâm hài hòa hương vị.",
    price: 39000,
    image: "/banh-mi-with-meatballs.jpg",
    category: "Sandwiches",
    rating: 4.4,
    totalReviews: 67,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Chay", "Healthy", "Bánh mì"],
  },
  {
    id: "dish_truffle_pho",
    restaurantId: "rest_1",
    name: "Phở Bò Sốt Nấm Truffle",
    description:
      "Thịt bắp bò hầm mềm chan sốt nấm truffle Ý, hành tây nướng caramel và tương đậu phộng.",
    price: 115000,
    image: "/vietnamese-beef-pho-bowl.jpg",
    category: "Noodles",
    rating: 4.9,
    totalReviews: 189,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Cao cấp", "Bò", "Truffle"],
  },
  {
    id: "dish_oxtail_pho",
    restaurantId: "rest_1",
    name: "Phở Đuôi Bò Hầm Than",
    description:
      "Đuôi bò hầm trên than hồng 6 giờ, nước phở đậm hương quế hồi, hành nướng và gừng già tạo vị ngọt.",
    price: 88000,
    image: "/vietnamese-beef-pho-bowl.jpg",
    category: "Noodles",
    rating: 4.7,
    totalReviews: 132,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Đặc biệt", "Bò", "Đậm đà"],
  },
  {
    id: "dish_scallop_rice",
    restaurantId: "rest_2",
    name: "Cơm Tấm Sò Điệp Nướng",
    description:
      "Sò điệp nướng bơ tỏi đặt trên cơm tấm hạt tơi, ăn cùng mỡ hành, tóp mỡ và nước mắm gừng.",
    price: 76000,
    image: "/vietnamese-broken-rice-with-grilled-pork.jpg",
    category: "Rice",
    rating: 4.6,
    totalReviews: 118,
    isAvailable: true,
    spicyLevel: "mild",
    tags: ["Hải sản", "Bơ tỏi", "Đặc sắc"],
  },
  {
    id: "dish_herbal_chicken_noodles",
    restaurantId: "rest_1",
    name: "Phở Gà Thảo Mộc",
    description:
      "Nước dùng gà hầm táo đỏ và kỳ tử, sợi phở dai cùng thịt gà xé thơm, thêm lá tía tô ấm bụng.",
    price: 36000,
    image: "/vietnamese-chicken-pho.jpg",
    category: "Noodles",
    rating: 4.3,
    totalReviews: 54,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Thanh", "Gà", "Buổi sáng"],
  },
  {
    id: "dish_mushroom_noodles",
    restaurantId: "rest_1",
    name: "Phở Nấm Rừng",
    description:
      "Phở chay với nước dùng ngọt từ nấm hương và củ cải, topping nấm đùi gà xào mè rang.",
    price: 34000,
    image: "/vietnamese-chicken-pho.jpg",
    category: "Noodles",
    rating: 4.2,
    totalReviews: 47,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Chay", "Nấm", "Thanh nhẹ"],
  },
  {
    id: "dish_sate_chicken_noodles",
    restaurantId: "rest_1",
    name: "Phở Gà Sa Tế",
    description:
      "Nước dùng gà cay nồng với sa tế Huế, gà xé thấm vị ăn kèm rau răm và giá trụng.",
    price: 38000,
    image: "/vietnamese-chicken-pho.jpg",
    category: "Noodles",
    rating: 4.4,
    totalReviews: 63,
    isAvailable: true,
    spicyLevel: "medium",
    tags: ["Cay", "Gà", "Đậm đà"],
  },
  {
    id: "dish_fried_rice_egg",
    restaurantId: "rest_2",
    name: "Cơm Chiên Trứng Muối",
    description:
      "Cơm chiên với lòng đỏ trứng muối, tôm khô và bắp ngọt, ăn kèm sốt tương ớt và rau củ hạt lựu.",
    price: 32000,
    image: "/grilled-pork-chop-with-rice.jpg",
    category: "Rice",
    rating: 4.3,
    totalReviews: 58,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Nhanh", "Trứng muối", "Tiện lợi"],
  },
  {
    id: "dish_rice_fish_caramel",
    restaurantId: "rest_2",
    name: "Cơm Cá Kho Tiêu",
    description:
      "Cá bống kho tiêu chưng trong nồi đất, nước sốt sánh đậm, ăn kèm cơm tấm nóng và dưa leo giòn.",
    price: 35000,
    image: "/vietnamese-broken-rice-with-grilled-pork.jpg",
    category: "Rice",
    rating: 4.1,
    totalReviews: 48,
    isAvailable: true,
    spicyLevel: "mild",
    tags: ["Gia đình", "Đậm đà", "Tiêu"],
  },
  {
    id: "dish_rice_chicken_crispy",
    restaurantId: "rest_2",
    name: "Cơm Gà Xối Mỡ",
    description:
      "Đùi gà chiên xối mỡ giòn rụm, cơm tấm rang bơ hành và nước mắm chua ngọt cân bằng vị.",
    price: 39000,
    image: "/grilled-pork-chop-with-rice.jpg",
    category: "Rice",
    rating: 4.2,
    totalReviews: 62,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Gà", "Giòn", "Đường phố"],
  },
  {
    id: "dish_rice_toasted_garlic",
    restaurantId: "rest_2",
    name: "Cơm Tấm Tỏi Phi",
    description:
      "Cơm tấm trộn tỏi phi vàng ruộm, tóp mỡ và hành lá, ăn kèm chả trứng và dưa chua.",
    price: 30000,
    image: "/vietnamese-broken-rice-with-grilled-pork.jpg",
    category: "Rice",
    rating: 4,
    totalReviews: 37,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Tiết kiệm", "Nhanh", "Đậm hương"],
  },
  {
    id: "dish_banh_mi_fish_cake",
    restaurantId: "rest_3",
    name: "Bánh Mì Chả Cá Nha Trang",
    description:
      "Chả cá chiên vàng, rau răm, dưa leo và sốt sa tế trong ổ bánh mì giòn rụm vừa nướng.",
    price: 28000,
    image: "/vietnamese-banh-mi-sandwich.jpg",
    category: "Sandwiches",
    rating: 4.4,
    totalReviews: 73,
    isAvailable: true,
    spicyLevel: "mild",
    tags: ["Biển", "Nhanh", "Đặc sản"],
  },
  {
    id: "dish_banh_mi_quail_egg",
    restaurantId: "rest_3",
    name: "Bánh Mì Trứng Cút Sốt Bơ",
    description:
      "Trứng cút chiên lòng đào, sốt bơ hành, pate béo và đồ chua cân bằng vị cho bữa sáng nhanh gọn.",
    price: 32000,
    image: "/vietnamese-banh-mi-sandwich.jpg",
    category: "Sandwiches",
    rating: 4.1,
    totalReviews: 42,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Buổi sáng", "Trứng", "Nhanh"],
  },
  {
    id: "dish_banh_mi_spicy_beef",
    restaurantId: "rest_3",
    name: "Bánh Mì Bò Lá Lốt",
    description:
      "Bò lá lốt nướng than thơm phức, đồ chua giòn và sốt me cay nhẹ khiến chiếc bánh mì khó cưỡng.",
    price: 35000,
    image: "/banh-mi-with-meatballs.jpg",
    category: "Sandwiches",
    rating: 4.3,
    totalReviews: 59,
    isAvailable: true,
    spicyLevel: "mild",
    tags: ["Bò", "Nướng", "Cay nhẹ"],
  },
]

export type DishFilterOption = {
  label: string
  value: string
}

export const cuisineOptions: DishFilterOption[] = [
  { label: "Tất cả", value: "all" },
  { label: "Món Việt", value: "Món Việt" },
  { label: "Món Hàn", value: "Món Hàn" },
  { label: "Món Nhật", value: "Món Nhật" },
  { label: "Món Trung", value: "Món Trung" },
  { label: "Món Thái", value: "Món Thái" },
  { label: "Fusion", value: "Fusion" },
]

export const ingredientOptions: DishFilterOption[] = [
  { label: "Tất cả", value: "all" },
  { label: "Bò", value: "Bò" },
  { label: "Gà", value: "Gà" },
  { label: "Heo", value: "Heo" },
  { label: "Tôm", value: "Tôm" },
  { label: "Cua", value: "Cua" },
  { label: "Cá", value: "Cá" },
  { label: "Hải sản", value: "Hải sản" },
  { label: "Chay", value: "Chay" },
]

export const methodOptions: DishFilterOption[] = [
  { label: "Tất cả", value: "all" },
  { label: "Chiên", value: "Chiên" },
  { label: "Xào", value: "Xào" },
  { label: "Luộc", value: "Luộc" },
  { label: "Hấp", value: "Hấp" },
  { label: "Nướng", value: "Nướng" },
  { label: "Kho", value: "Kho" },
  { label: "Hầm", value: "Hầm" },
  { label: "Trộn", value: "Trộn" },
]

export const flavorOptions: DishFilterOption[] = [
  { label: "Tất cả", value: "all" },
  { label: "Thanh", value: "Thanh" },
  { label: "Cay", value: "Cay" },
  { label: "Mặn", value: "Mặn" },
  { label: "Ngọt", value: "Ngọt" },
  { label: "Chua", value: "Chua" },
  { label: "Đậm đà", value: "Đậm đà" },
  { label: "Béo", value: "Béo" },
]

export const priceOptions: DishFilterOption[] = [
  { label: "Tất cả", value: "all" },
  { label: "Dưới 40k", value: "under_40" },
  { label: "40k - 60k", value: "40_60" },
  { label: "Trên 60k", value: "over_60" },
]

type DishMeta = {
  cuisine: string
  mainIngredients: string[]
  cookMethods: string[]
  flavorProfiles: string[]
}

export const dishMetadata: Record<string, DishMeta> = {
  dish_1: {
    cuisine: "Món Việt",
    mainIngredients: ["Bò"],
    cookMethods: ["Hầm"],
    flavorProfiles: ["Đậm đà", "Thanh"],
  },
  dish_2: {
    cuisine: "Món Việt",
    mainIngredients: ["Gà"],
    cookMethods: ["Hầm"],
    flavorProfiles: ["Thanh", "Ngọt"],
  },
  dish_3: {
    cuisine: "Món Việt",
    mainIngredients: ["Heo"],
    cookMethods: ["Nướng", "Kho"],
    flavorProfiles: ["Đậm đà", "Mặn"],
  },
  dish_4: {
    cuisine: "Món Việt",
    mainIngredients: ["Heo"],
    cookMethods: ["Nướng"],
    flavorProfiles: ["Đậm đà", "Ngọt"],
  },
  dish_5: {
    cuisine: "Món Việt",
    mainIngredients: ["Heo"],
    cookMethods: ["Trộn"],
    flavorProfiles: ["Đậm đà", "Béo"],
  },
  dish_6: {
    cuisine: "Món Việt",
    mainIngredients: ["Heo"],
    cookMethods: ["Kho"],
    flavorProfiles: ["Đậm đà", "Ngọt"],
  },
  dish_wagyu_pho: {
    cuisine: "Fusion",
    mainIngredients: ["Bò"],
    cookMethods: ["Hầm"],
    flavorProfiles: ["Đậm đà", "Béo"],
  },
  dish_golden_chicken_pho: {
    cuisine: "Món Việt",
    mainIngredients: ["Gà"],
    cookMethods: ["Hầm"],
    flavorProfiles: ["Thanh", "Ngọt"],
  },
  dish_crispy_short_rib: {
    cuisine: "Món Việt",
    mainIngredients: ["Heo"],
    cookMethods: ["Nướng", "Chiên"],
    flavorProfiles: ["Đậm đà", "Mặn"],
  },
  dish_salted_egg_rice: {
    cuisine: "Món Việt",
    mainIngredients: ["Heo"],
    cookMethods: ["Nướng", "Chiên"],
    flavorProfiles: ["Béo", "Mặn"],
  },
  dish_sweety_pork_rice: {
    cuisine: "Món Việt",
    mainIngredients: ["Heo"],
    cookMethods: ["Kho"],
    flavorProfiles: ["Ngọt", "Đậm đà"],
  },
  dish_banh_mi_pate_foie: {
    cuisine: "Món Việt",
    mainIngredients: ["Heo"],
    cookMethods: ["Trộn"],
    flavorProfiles: ["Béo", "Đậm đà"],
  },
  dish_banh_mi_grilled_chicken: {
    cuisine: "Món Việt",
    mainIngredients: ["Gà"],
    cookMethods: ["Nướng"],
    flavorProfiles: ["Đậm đà", "Thanh"],
  },
  dish_banh_mi_caramel_pork: {
    cuisine: "Món Việt",
    mainIngredients: ["Heo"],
    cookMethods: ["Kho"],
    flavorProfiles: ["Ngọt", "Đậm đà"],
  },
  dish_spicy_pho_sate: {
    cuisine: "Món Thái",
    mainIngredients: ["Bò"],
    cookMethods: ["Hầm"],
    flavorProfiles: ["Cay", "Mặn"],
  },
  dish_crab_pho: {
    cuisine: "Món Việt",
    mainIngredients: ["Cua", "Hải sản"],
    cookMethods: ["Hầm"],
    flavorProfiles: ["Thanh", "Ngọt"],
  },
  dish_pandan_rice: {
    cuisine: "Fusion",
    mainIngredients: ["Tôm", "Hải sản"],
    cookMethods: ["Hấp", "Xào"],
    flavorProfiles: ["Thanh", "Đậm đà"],
  },
  dish_veggie_banh_mi: {
    cuisine: "Fusion",
    mainIngredients: ["Chay"],
    cookMethods: ["Xào", "Trộn"],
    flavorProfiles: ["Thanh", "Đậm đà"],
  },
  dish_truffle_pho: {
    cuisine: "Fusion",
    mainIngredients: ["Bò"],
    cookMethods: ["Hầm"],
    flavorProfiles: ["Đậm đà", "Béo"],
  },
  dish_oxtail_pho: {
    cuisine: "Món Việt",
    mainIngredients: ["Bò"],
    cookMethods: ["Hầm"],
    flavorProfiles: ["Đậm đà", "Béo"],
  },
  dish_scallop_rice: {
    cuisine: "Món Nhật",
    mainIngredients: ["Hải sản"],
    cookMethods: ["Nướng"],
    flavorProfiles: ["Béo", "Mặn"],
  },
  dish_herbal_chicken_noodles: {
    cuisine: "Món Việt",
    mainIngredients: ["Gà"],
    cookMethods: ["Hầm"],
    flavorProfiles: ["Thanh", "Ngọt"],
  },
  dish_mushroom_noodles: {
    cuisine: "Món Việt",
    mainIngredients: ["Chay"],
    cookMethods: ["Hầm"],
    flavorProfiles: ["Thanh"],
  },
  dish_sate_chicken_noodles: {
    cuisine: "Món Thái",
    mainIngredients: ["Gà"],
    cookMethods: ["Hầm"],
    flavorProfiles: ["Cay", "Đậm đà"],
  },
  dish_fried_rice_egg: {
    cuisine: "Món Việt",
    mainIngredients: ["Tôm"],
    cookMethods: ["Chiên"],
    flavorProfiles: ["Mặn", "Béo"],
  },
  dish_rice_fish_caramel: {
    cuisine: "Món Việt",
    mainIngredients: ["Cá"],
    cookMethods: ["Kho"],
    flavorProfiles: ["Mặn", "Đậm đà"],
  },
  dish_rice_chicken_crispy: {
    cuisine: "Món Việt",
    mainIngredients: ["Gà"],
    cookMethods: ["Chiên", "Nướng"],
    flavorProfiles: ["Đậm đà", "Béo"],
  },
  dish_rice_toasted_garlic: {
    cuisine: "Món Việt",
    mainIngredients: ["Heo"],
    cookMethods: ["Chiên"],
    flavorProfiles: ["Mặn", "Đậm đà"],
  },
  dish_banh_mi_fish_cake: {
    cuisine: "Món Việt",
    mainIngredients: ["Cá", "Hải sản"],
    cookMethods: ["Chiên"],
    flavorProfiles: ["Mặn", "Đậm đà"],
  },
  dish_banh_mi_quail_egg: {
    cuisine: "Món Việt",
    mainIngredients: ["Gà"],
    cookMethods: ["Chiên"],
    flavorProfiles: ["Béo", "Ngọt"],
  },
  dish_banh_mi_spicy_beef: {
    cuisine: "Món Việt",
    mainIngredients: ["Bò"],
    cookMethods: ["Nướng"],
    flavorProfiles: ["Cay", "Đậm đà"],
  },
}

export const mockOrders: Order[] = [
  {
    id: "order_1",
    userId: "user_1",
    restaurantId: "rest_1",
    items: [
      {
        dishId: "dish_1",
        dishName: "Phở Bò Tái",
        dishImage: "/beef-pho.png",
        quantity: 2,
        price: 55000,
      },
    ],
    status: "completed",
    totalAmount: 110000,
    deliveryAddress: {
      id: "addr_1",
      userId: "user_1",
      label: "Home",
      street: "789 Nguyễn Trãi",
      city: "TP.HCM",
      district: "Q.5",
      isDefault: true,
    },
    createdAt: "2024-10-10T10:00:00Z",
    updatedAt: "2024-10-10T11:30:00Z",
  },
]

export const mockReviews: Review[] = [
  {
    id: "review_1",
    userId: "user_1",
    userName: "Nguyễn Văn A",
    dishId: "dish_1",
    orderId: "order_1",
    rating: 5,
    comment: "Phở rất ngon, nước dùng đậm đà!",
    createdAt: "2024-10-10T12:00:00Z",
  },
  {
    id: "review_2",
    userId: "user_2",
    userName: "Lê Thu Trang",
    dishId: "dish_1",
    orderId: "order_2",
    rating: 4,
    comment: "Thịt bò mềm, nước dùng hơi mặn nhưng vẫn ổn.",
    createdAt: "2024-10-11T09:15:00Z",
  },
  {
    id: "review_3",
    userId: "user_3",
    userName: "Phạm Minh Đức",
    dishId: "dish_3",
    orderId: "order_3",
    rating: 5,
    comment: "Cơm tấm ngon tuyệt, sườn nướng thơm và mềm.",
    createdAt: "2024-10-09T18:45:00Z",
  },
  {
    id: "review_4",
    userId: "user_4",
    userName: "Trần Gia Huy",
    dishId: "dish_5",
    orderId: "order_4",
    rating: 5,
    comment: "Bánh mì giòn, nhân đầy đủ và tươi, rất đáng thử.",
    createdAt: "2024-10-08T14:20:00Z",
  },
  {
    id: "review_5",
    userId: "user_5",
    userName: "Vũ Ngọc Hà",
    dishId: "dish_3",
    orderId: "order_5",
    rating: 4,
    comment: "Khẩu phần nhiều, nước mắm pha vừa miệng.",
    createdAt: "2024-10-07T11:10:00Z",
  },
  {
    id: "review_6",
    userId: "user_6",
    userName: "Đinh Tuấn Kiệt",
    dishId: "dish_6",
    orderId: "order_6",
    rating: 3,
    comment: "Bánh mì xíu mại ngon nhưng hơi ít nước sốt.",
    createdAt: "2024-10-05T16:00:00Z",
  },
]

export const mockDashboardStats: DashboardStats = {
  totalRevenue: 125000000,
  totalOrders: 1234,
  totalUsers: 567,
  totalRestaurants: 45,
  revenueChange: 12.5,
  ordersChange: 8.3,
  usersChange: 15.2,
}

export const mockRevenueData: RevenueData[] = [
  { date: "2024-10-01", revenue: 3500000, orders: 45 },
  { date: "2024-10-02", revenue: 4200000, orders: 52 },
  { date: "2024-10-03", revenue: 3800000, orders: 48 },
  { date: "2024-10-04", revenue: 4500000, orders: 58 },
  { date: "2024-10-05", revenue: 5200000, orders: 65 },
  { date: "2024-10-06", revenue: 6100000, orders: 78 },
  { date: "2024-10-07", revenue: 5800000, orders: 72 },
]

const generateDynamicReviews = (dishes: Dish[]): Review[] => {
  if (!dishes.length) return []

  const reviewers = [
    { id: "user_quynh", name: "Lê Mỹ Quỳnh" },
    { id: "user_thinh", name: "Phạm Quốc Thịnh" },
    { id: "user_anhthu", name: "Ngô Ánh Thư" },
    { id: "user_danh", name: "Trần Hữu Danh" },
    { id: "user_tuananh", name: "Vũ Tuấn Anh" },
    { id: "user_minhanh", name: "Bùi Minh Ánh" },
    { id: "user_linh", name: "Đặng Diễm Linh" },
    { id: "user_vy", name: "Phạm Gia Vy" },
  ]

  const comments = [
    "Hương vị cực kỳ ấn tượng, nêm nếm vừa miệng và phần ăn rất đầy đặn.",
    "Giao hàng nhanh, món ăn tới nơi vẫn còn nóng hổi và thơm phức.",
    "Giá hơi cao nhưng chất lượng xứng đáng, sẽ đặt lại nhiều lần nữa.",
    "Rau ăn kèm tươi, nước sốt đậm đà, tổng thể rất hài lòng.",
    "Phần ăn trình bày bắt mắt, topping phong phú khiến ăn không bị ngán.",
    "Gia vị hài hòa, không quá mặn cũng không quá nhạt, dễ ăn cho cả nhà.",
    "Sốt đặc trưng rất ngon, nhưng mình mong thêm chút rau sống nữa là hoàn hảo.",
    "Ăn tới miếng cuối cùng vẫn thấy ngon, sẽ giới thiệu cho bạn bè thử.",
  ]

  const baseDate = Date.parse("2024-10-20T12:00:00Z")

  return dishes.flatMap((dish, dishIndex) => {
    const reviewCount = 3 // Tạo 3 review cho mỗi món
    return Array.from({ length: reviewCount }, (_, reviewIndex) => {
      const reviewer = reviewers[(dishIndex + reviewIndex) % reviewers.length]
      const comment = comments[(dishIndex * 2 + reviewIndex) % comments.length]
      const ratingBase = dish.rating
      const adjustment = reviewIndex === 0 ? 0.2 : reviewIndex === 1 ? -0.1 : 0
      const rating = Math.min(5, Math.max(3.5, Math.round((ratingBase + adjustment) * 10) / 10))
      const createdAt = new Date(baseDate - (dishIndex * 3 + reviewIndex) * 86400000).toISOString()

      return {
        id: `gen_review_${dish.id}_${reviewIndex}`,
        userId: reviewer.id,
        userName: reviewer.name,
        dishId: dish.id,
        orderId: `gen_order_${dish.id}_${reviewIndex}`,
        rating,
        comment,
        createdAt,
      }
    })
  })
}

// Gọi hàm để tạo review
const generatedReviews = generateDynamicReviews(mockDishes)

// Tạo một mảng tổng hợp chứa cả review gốc và review vừa tạo
export const allMockReviews: Review[] = [...mockReviews, ...generatedReviews]