import type { Restaurant, Dish, Order, Review, DashboardStats, RevenueData } from "@/types"

export const mockRestaurants: Restaurant[] = [
  {
    id: "rest_1",
    name: "Phở Hà Nội",
    description: "Authentic Vietnamese pho with traditional recipes",
    image: "/vietnamese-pho-restaurant.png",
    address: "123 Nguyễn Huệ, Q.1, TP.HCM",
    phone: "0281234567",
    rating: 4.5,
    totalReviews: 234,
    isActive: true,
    openTime: "06:00",
    closeTime: "22:00",
    categories: ["Vietnamese", "Noodles"],
  },
  {
    id: "rest_2",
    name: "Cơm Tấm Sài Gòn",
    description: "Delicious broken rice with grilled pork",
    image: "/vietnamese-broken-rice-restaurant.jpg",
    address: "456 Lê Lợi, Q.1, TP.HCM",
    phone: "0281234568",
    rating: 4.7,
    totalReviews: 189,
    isActive: true,
    openTime: "07:00",
    closeTime: "21:00",
    categories: ["Vietnamese", "Rice"],
  },
  {
    id: "rest_3",
    name: "Bánh Mì 362",
    description: "Famous Vietnamese baguette sandwiches",
    image: "/vietnamese-banh-mi-sandwich-shop.jpg",
    address: "362 Hai Bà Trưng, Q.3, TP.HCM",
    phone: "0281234569",
    rating: 4.8,
    totalReviews: 456,
    isActive: true,
    openTime: "06:00",
    closeTime: "20:00",
    categories: ["Vietnamese", "Sandwiches"],
  },
]

export const mockDishes: Dish[] = [
  {
    id: "dish_1",
    restaurantId: "rest_1",
    name: "Phở Bò Tái",
    description: "Beef pho with rare beef slices",
    price: 55000,
    image: "/vietnamese-beef-pho-bowl.jpg",
    category: "Noodles",
    rating: 4.6,
    totalReviews: 89,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Popular", "Bò", "Món nước", "Đậm đà"],
  },
  {
    id: "dish_2",
    restaurantId: "rest_1",
    name: "Phở Gà",
    description: "Chicken pho with tender chicken",
    price: 50000,
    image: "/vietnamese-chicken-pho.jpg",
    category: "Noodles",
    rating: 4.4,
    totalReviews: 67,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Gà", "Món nước", "Thanh nhẹ"],
  },
  {
    id: "dish_3",
    restaurantId: "rest_2",
    name: "Cơm Tấm Sườn Bì Chả",
    description: "Broken rice with grilled pork, shredded pork skin, and egg meatloaf",
    price: 45000,
    image: "/vietnamese-broken-rice-with-grilled-pork.jpg",
    category: "Rice",
    rating: 4.7,
    totalReviews: 123,
    isAvailable: true,
    spicyLevel: "mild",
    tags: ["Popular", "Heo", "Món Việt", "Nướng"],
  },
  {
    id: "dish_4",
    restaurantId: "rest_2",
    name: "Cơm Tấm Sườn Nướng",
    description: "Broken rice with grilled pork chop",
    price: 40000,
    image: "/grilled-pork-chop-with-rice.jpg",
    category: "Rice",
    rating: 4.5,
    totalReviews: 98,
    isAvailable: true,
    spicyLevel: "none",
    tags: ["Heo", "Món Việt", "Nướng"],
  },
  {
    id: "dish_5",
    restaurantId: "rest_3",
    name: "Bánh Mì Thịt Nguội",
    description: "Vietnamese baguette with cold cuts",
    price: 25000,
    image: "/vietnamese-banh-mi-sandwich.jpg",
    category: "Sandwiches",
    rating: 4.8,
    totalReviews: 234,
    isAvailable: true,
    spicyLevel: "mild",
    tags: ["Popular", "Bánh mì", "Nhanh"],
  },
  {
    id: "dish_6",
    restaurantId: "rest_3",
    name: "Bánh Mì Xíu Mại",
    description: "Vietnamese baguette with meatballs",
    price: 30000,
    image: "/banh-mi-with-meatballs.jpg",
    category: "Sandwiches",
    rating: 4.6,
    totalReviews: 156,
    isAvailable: true,
    spicyLevel: "medium",
    tags: ["Xíu mại", "Bánh mì", "Nhanh"],
  },
]

export const mockOrders: Order[] = [
  {
    id: "order_1",
    userId: "user_1",
    restaurantId: "rest_1",
    items: [
      {
        dishId: "dish_1",
        dishName: "Phở Bò Tái",
        dishImage: "/beef-pho.png",
        quantity: 2,
        price: 55000,
      },
    ],
    status: "completed",
    totalAmount: 110000,
    deliveryAddress: {
      id: "addr_1",
      userId: "user_1",
      label: "Home",
      street: "789 Nguyễn Trãi",
      city: "TP.HCM",
      district: "Q.5",
      isDefault: true,
    },
    createdAt: "2024-10-10T10:00:00Z",
    updatedAt: "2024-10-10T11:30:00Z",
  },
]

export const mockReviews: Review[] = [
  {
    id: "review_1",
    userId: "user_1",
    userName: "Nguyễn Văn A",
    dishId: "dish_1",
    orderId: "order_1",
    rating: 5,
    comment: "Phở rất ngon, nước dùng đậm đà!",
    createdAt: "2024-10-10T12:00:00Z",
  },
  {
    id: "review_2",
    userId: "user_2",
    userName: "Lê Thu Trang",
    dishId: "dish_1",
    orderId: "order_2",
    rating: 4,
    comment: "Thịt bò mềm, nước dùng hơi mặn nhưng vẫn ổn.",
    createdAt: "2024-10-11T09:15:00Z",
  },
  {
    id: "review_3",
    userId: "user_3",
    userName: "Phạm Minh Đức",
    dishId: "dish_3",
    orderId: "order_3",
    rating: 5,
    comment: "Cơm tấm ngon tuyệt, sườn nướng thơm và mềm.",
    createdAt: "2024-10-09T18:45:00Z",
  },
  {
    id: "review_4",
    userId: "user_4",
    userName: "Trần Gia Huy",
    dishId: "dish_5",
    orderId: "order_4",
    rating: 5,
    comment: "Bánh mì giòn, nhân đầy đủ và tươi, rất đáng thử.",
    createdAt: "2024-10-08T14:20:00Z",
  },
  {
    id: "review_5",
    userId: "user_5",
    userName: "Vũ Ngọc Hà",
    dishId: "dish_3",
    orderId: "order_5",
    rating: 4,
    comment: "Khẩu phần nhiều, nước mắm pha vừa miệng.",
    createdAt: "2024-10-07T11:10:00Z",
  },
  {
    id: "review_6",
    userId: "user_6",
    userName: "Đinh Tuấn Kiệt",
    dishId: "dish_6",
    orderId: "order_6",
    rating: 3,
    comment: "Bánh mì xíu mại ngon nhưng hơi ít nước sốt.",
    createdAt: "2024-10-05T16:00:00Z",
  },
]

export const mockDashboardStats: DashboardStats = {
  totalRevenue: 125000000,
  totalOrders: 1234,
  totalUsers: 567,
  totalRestaurants: 45,
  revenueChange: 12.5,
  ordersChange: 8.3,
  usersChange: 15.2,
}

export const mockRevenueData: RevenueData[] = [
  { date: "2024-10-01", revenue: 3500000, orders: 45 },
  { date: "2024-10-02", revenue: 4200000, orders: 52 },
  { date: "2024-10-03", revenue: 3800000, orders: 48 },
  { date: "2024-10-04", revenue: 4500000, orders: 58 },
  { date: "2024-10-05", revenue: 5200000, orders: 65 },
  { date: "2024-10-06", revenue: 6100000, orders: 78 },
  { date: "2024-10-07", revenue: 5800000, orders: 72 },
]
